# Live smoke test for the Podman-provisioned docling-serve path.
#
# Brings up a real server with doclr_setup(engine = "podman") and converts a
# small document through the real HTTP API. Linux-only: Podman machine (the
# VM step doclr_setup() drives on macOS/Windows) needs nested virtualization,
# which GitHub-hosted macOS and Windows runners don't support. Run by
# .github/workflows/podman-smoke.yaml; never sourced by the package itself.

pkgload::load_all(quiet = TRUE)

cli::cli_h1("Starting docling-serve via Podman")
client <- doclr_setup(engine = "podman", interactive = FALSE)
stopifnot(doclr_health(client))
cli::cli_alert_success("Server is healthy at {.url {client$url}}")

sample_path <- tempfile(fileext = ".md")
writeLines(
  c("# doclr smoke test", "", "Generated by the podman-smoke workflow."),
  sample_path
)

cli::cli_h1("Converting a sample document")
doc <- doclr_convert_file(sample_path, client = client)
stopifnot(is_doclr_document(doc))
stopifnot(identical(doc$status, "success"))

md <- as_markdown(doc)
stopifnot(is.character(md), nchar(md) > 0)
cli::cli_alert_success("Conversion round-trip succeeded ({nchar(md)} chars).")

cli::cli_h1("Tearing down")
doclr_server_stop()
